baseURL: https://jo3-l.github.io
title: Joe's Blog
copyright: Content released under CC-BY-SA
theme: PaperMod
paginate: 3

params:
  homeInfoParams:
    title: Hey there!
    content: |
      I'm Joseph Liu, an incoming computer science undergraduate at the University of Waterloo.
      Welcome to my small slice of the web :) Here, I occasionally blog about math, programming, and
      whatever else piques my interest.

      If you would like to know more about me, head over to my [about page](/about). To contact me,
      email me at `jliu1602 [at] gmail.com`; I am also active on Discord as `jo3_l`.

  title: Joe's Blog
  author: Joseph Liu
  description: My small slice of the web—occasional musings on math, programming, and other topics
  dateFormat: '02 January 2006'
  socialIcons:
    - name: github
      url: https://github.com/jo3-l/
    - name: email
      url: mailto:jliu1602@gmail.com
  showCodeCopyButtons: true

menu:
  main:
    - identifier: Home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: reading-log
      name: Reading Log
      url: /reading-log/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
