baseURL: https://jo3-l.dev
title: Joe's Blog
copyright: Content licensed under CC-BY-SA
theme: PaperMod
pagination:
  pagerSize: 5

params:
  homeInfoParams:
    title: Hi there!
    content: |
      I'm Joseph Liu, a first-year CS student at the University of Waterloo.
      Welcome to my small slice of the web :) Here, I occasionally blog about math, programming, and
      whatever else piques my interest.

      If you would like to know more about me or my projects, head over to my [about page](/about).
      To contact me, email me at `jliu1602 [at] gmail.com`; I am also active on Discord as `jo3_l`.

  title: Joe's Blog
  author: Joseph Liu
  description: My small slice of the web—occasional musings on math, programming, and other topics
  dateFormat: "02 January 2006"
  social: true
  socialIcons:
    - name: github
      url: https://github.com/jo3-l/
    - name: email
      url: mailto:jliu1602@gmail.com
    - name: discord
      url: https://discord.com/users/621907351267442698
    - name: linkedin
      url: https://www.linkedin.com/in/joseph-h-liu/
  showCodeCopyButtons: true
  showWordCount: true

menu:
  main:
    - identifier: Home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: reading-log
      name: Reading Log
      url: /reading-log/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
