baseURL: https://jo3-l.github.io
title: Joe's Blog
theme: PaperMod
paginate: 3

params:
  homeInfoParams:
    title: Hey there!
    content: |
      I'm Joseph Liu, an incoming computer science undergraduate at the University of Waterloo.
      Welcome to my own small slice of the web :) Here, I occasionally blog about math, programming,
      and whatever else piques my interest.

      If you would like to know more about me, head over to my [about page](/about). To contact me,
      email me at `jo3.l.dev [at] outlook.com`; I am also active on Discord as `jo3_l`.

  title: Joe's Blog
  author: Joseph Liu
  description: My small slice of the web
  dateFormat: '02 January 2006'
  socialIcons:
    - name: github
      url: https://github.com/jo3-l/
    - name: email
      url: mailto:jo3.l.dev@outlook.com

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: archive
      name: Archive
      url: /posts/
      weight: 3

markup:
  highlight:
    codeFences: true
    noClasses: true
    style: xcode-dark
  goldmark:
    renderer:
      unsafe: true
