baseURL: https://jo3-l.github.io
languageCode: en-us
title: Joe's Blog
theme: anubis
paginate: 3

params:
  author: Joe L.
  description: Student, CS enthusiast, eternal nitpicker. Occasional competitive programmer.
  dateFormat: "2006-01-02"
  style: auto-without-switcher
  rssAsSocialIcon: true
  social:
    - id: github
      url: https://github.com/jo3-l/
    - id: email
      url: mailto:jo3.l.dev@outlook.com

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: archive
      name: Archive
      url: /posts/
      weight: 3

markup:
  highlight:
    codeFences: true
    noClasses: true
    style: xcode-dark
  goldmark:
    renderer:
      unsafe: true
